name: HNtest
favicon: null
layout_spectrum: 0.17718436592258513
typography_spectrum: 0.6253991473931819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9238280635327101
  lightness: 0.006868994794785976
  saturation: 0.7283292897045612
  rhythmicContrast: 0.5432261435780674
purpose: []
