name: HNtest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#888888'
    - '#a6a6a6'
    - '#c2c2c2'
    - '#a0dbf2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
